# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _norms_and_vecs
else:
    import _norms_and_vecs

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _norms_and_vecs.delete_SwigPyIterator

    def value(self):
        return _norms_and_vecs.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _norms_and_vecs.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _norms_and_vecs.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _norms_and_vecs.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _norms_and_vecs.SwigPyIterator_equal(self, x)

    def copy(self):
        return _norms_and_vecs.SwigPyIterator_copy(self)

    def next(self):
        return _norms_and_vecs.SwigPyIterator_next(self)

    def __next__(self):
        return _norms_and_vecs.SwigPyIterator___next__(self)

    def previous(self):
        return _norms_and_vecs.SwigPyIterator_previous(self)

    def advance(self, n):
        return _norms_and_vecs.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _norms_and_vecs.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _norms_and_vecs.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _norms_and_vecs.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _norms_and_vecs.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _norms_and_vecs.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _norms_and_vecs.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _norms_and_vecs:
_norms_and_vecs.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _norms_and_vecs.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _norms_and_vecs.IntVector___nonzero__(self)

    def __bool__(self):
        return _norms_and_vecs.IntVector___bool__(self)

    def __len__(self):
        return _norms_and_vecs.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _norms_and_vecs.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _norms_and_vecs.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _norms_and_vecs.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _norms_and_vecs.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _norms_and_vecs.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _norms_and_vecs.IntVector___setitem__(self, *args)

    def pop(self):
        return _norms_and_vecs.IntVector_pop(self)

    def append(self, x):
        return _norms_and_vecs.IntVector_append(self, x)

    def empty(self):
        return _norms_and_vecs.IntVector_empty(self)

    def size(self):
        return _norms_and_vecs.IntVector_size(self)

    def swap(self, v):
        return _norms_and_vecs.IntVector_swap(self, v)

    def begin(self):
        return _norms_and_vecs.IntVector_begin(self)

    def end(self):
        return _norms_and_vecs.IntVector_end(self)

    def rbegin(self):
        return _norms_and_vecs.IntVector_rbegin(self)

    def rend(self):
        return _norms_and_vecs.IntVector_rend(self)

    def clear(self):
        return _norms_and_vecs.IntVector_clear(self)

    def get_allocator(self):
        return _norms_and_vecs.IntVector_get_allocator(self)

    def pop_back(self):
        return _norms_and_vecs.IntVector_pop_back(self)

    def erase(self, *args):
        return _norms_and_vecs.IntVector_erase(self, *args)

    def __init__(self, *args):
        _norms_and_vecs.IntVector_swiginit(self, _norms_and_vecs.new_IntVector(*args))

    def push_back(self, x):
        return _norms_and_vecs.IntVector_push_back(self, x)

    def front(self):
        return _norms_and_vecs.IntVector_front(self)

    def back(self):
        return _norms_and_vecs.IntVector_back(self)

    def assign(self, n, x):
        return _norms_and_vecs.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _norms_and_vecs.IntVector_resize(self, *args)

    def insert(self, *args):
        return _norms_and_vecs.IntVector_insert(self, *args)

    def reserve(self, n):
        return _norms_and_vecs.IntVector_reserve(self, n)

    def capacity(self):
        return _norms_and_vecs.IntVector_capacity(self)
    __swig_destroy__ = _norms_and_vecs.delete_IntVector

# Register IntVector in _norms_and_vecs:
_norms_and_vecs.IntVector_swigregister(IntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _norms_and_vecs.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _norms_and_vecs.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _norms_and_vecs.DoubleVector___bool__(self)

    def __len__(self):
        return _norms_and_vecs.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _norms_and_vecs.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _norms_and_vecs.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _norms_and_vecs.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _norms_and_vecs.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _norms_and_vecs.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _norms_and_vecs.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _norms_and_vecs.DoubleVector_pop(self)

    def append(self, x):
        return _norms_and_vecs.DoubleVector_append(self, x)

    def empty(self):
        return _norms_and_vecs.DoubleVector_empty(self)

    def size(self):
        return _norms_and_vecs.DoubleVector_size(self)

    def swap(self, v):
        return _norms_and_vecs.DoubleVector_swap(self, v)

    def begin(self):
        return _norms_and_vecs.DoubleVector_begin(self)

    def end(self):
        return _norms_and_vecs.DoubleVector_end(self)

    def rbegin(self):
        return _norms_and_vecs.DoubleVector_rbegin(self)

    def rend(self):
        return _norms_and_vecs.DoubleVector_rend(self)

    def clear(self):
        return _norms_and_vecs.DoubleVector_clear(self)

    def get_allocator(self):
        return _norms_and_vecs.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _norms_and_vecs.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _norms_and_vecs.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _norms_and_vecs.DoubleVector_swiginit(self, _norms_and_vecs.new_DoubleVector(*args))

    def push_back(self, x):
        return _norms_and_vecs.DoubleVector_push_back(self, x)

    def front(self):
        return _norms_and_vecs.DoubleVector_front(self)

    def back(self):
        return _norms_and_vecs.DoubleVector_back(self)

    def assign(self, n, x):
        return _norms_and_vecs.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _norms_and_vecs.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _norms_and_vecs.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _norms_and_vecs.DoubleVector_reserve(self, n)

    def capacity(self):
        return _norms_and_vecs.DoubleVector_capacity(self)
    __swig_destroy__ = _norms_and_vecs.delete_DoubleVector

# Register DoubleVector in _norms_and_vecs:
_norms_and_vecs.DoubleVector_swigregister(DoubleVector)

class DoubleVectorVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _norms_and_vecs.DoubleVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _norms_and_vecs.DoubleVectorVector___nonzero__(self)

    def __bool__(self):
        return _norms_and_vecs.DoubleVectorVector___bool__(self)

    def __len__(self):
        return _norms_and_vecs.DoubleVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _norms_and_vecs.DoubleVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _norms_and_vecs.DoubleVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _norms_and_vecs.DoubleVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _norms_and_vecs.DoubleVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _norms_and_vecs.DoubleVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _norms_and_vecs.DoubleVectorVector___setitem__(self, *args)

    def pop(self):
        return _norms_and_vecs.DoubleVectorVector_pop(self)

    def append(self, x):
        return _norms_and_vecs.DoubleVectorVector_append(self, x)

    def empty(self):
        return _norms_and_vecs.DoubleVectorVector_empty(self)

    def size(self):
        return _norms_and_vecs.DoubleVectorVector_size(self)

    def swap(self, v):
        return _norms_and_vecs.DoubleVectorVector_swap(self, v)

    def begin(self):
        return _norms_and_vecs.DoubleVectorVector_begin(self)

    def end(self):
        return _norms_and_vecs.DoubleVectorVector_end(self)

    def rbegin(self):
        return _norms_and_vecs.DoubleVectorVector_rbegin(self)

    def rend(self):
        return _norms_and_vecs.DoubleVectorVector_rend(self)

    def clear(self):
        return _norms_and_vecs.DoubleVectorVector_clear(self)

    def get_allocator(self):
        return _norms_and_vecs.DoubleVectorVector_get_allocator(self)

    def pop_back(self):
        return _norms_and_vecs.DoubleVectorVector_pop_back(self)

    def erase(self, *args):
        return _norms_and_vecs.DoubleVectorVector_erase(self, *args)

    def __init__(self, *args):
        _norms_and_vecs.DoubleVectorVector_swiginit(self, _norms_and_vecs.new_DoubleVectorVector(*args))

    def push_back(self, x):
        return _norms_and_vecs.DoubleVectorVector_push_back(self, x)

    def front(self):
        return _norms_and_vecs.DoubleVectorVector_front(self)

    def back(self):
        return _norms_and_vecs.DoubleVectorVector_back(self)

    def assign(self, n, x):
        return _norms_and_vecs.DoubleVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _norms_and_vecs.DoubleVectorVector_resize(self, *args)

    def insert(self, *args):
        return _norms_and_vecs.DoubleVectorVector_insert(self, *args)

    def reserve(self, n):
        return _norms_and_vecs.DoubleVectorVector_reserve(self, n)

    def capacity(self):
        return _norms_and_vecs.DoubleVectorVector_capacity(self)
    __swig_destroy__ = _norms_and_vecs.delete_DoubleVectorVector

# Register DoubleVectorVector in _norms_and_vecs:
_norms_and_vecs.DoubleVectorVector_swigregister(DoubleVectorVector)

class DoubleMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _norms_and_vecs.DoubleMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _norms_and_vecs.DoubleMap___nonzero__(self)

    def __bool__(self):
        return _norms_and_vecs.DoubleMap___bool__(self)

    def __len__(self):
        return _norms_and_vecs.DoubleMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _norms_and_vecs.DoubleMap___getitem__(self, key)

    def __delitem__(self, key):
        return _norms_and_vecs.DoubleMap___delitem__(self, key)

    def has_key(self, key):
        return _norms_and_vecs.DoubleMap_has_key(self, key)

    def keys(self):
        return _norms_and_vecs.DoubleMap_keys(self)

    def values(self):
        return _norms_and_vecs.DoubleMap_values(self)

    def items(self):
        return _norms_and_vecs.DoubleMap_items(self)

    def __contains__(self, key):
        return _norms_and_vecs.DoubleMap___contains__(self, key)

    def key_iterator(self):
        return _norms_and_vecs.DoubleMap_key_iterator(self)

    def value_iterator(self):
        return _norms_and_vecs.DoubleMap_value_iterator(self)

    def __setitem__(self, *args):
        return _norms_and_vecs.DoubleMap___setitem__(self, *args)

    def asdict(self):
        return _norms_and_vecs.DoubleMap_asdict(self)

    def __init__(self, *args):
        _norms_and_vecs.DoubleMap_swiginit(self, _norms_and_vecs.new_DoubleMap(*args))

    def empty(self):
        return _norms_and_vecs.DoubleMap_empty(self)

    def size(self):
        return _norms_and_vecs.DoubleMap_size(self)

    def swap(self, v):
        return _norms_and_vecs.DoubleMap_swap(self, v)

    def begin(self):
        return _norms_and_vecs.DoubleMap_begin(self)

    def end(self):
        return _norms_and_vecs.DoubleMap_end(self)

    def rbegin(self):
        return _norms_and_vecs.DoubleMap_rbegin(self)

    def rend(self):
        return _norms_and_vecs.DoubleMap_rend(self)

    def clear(self):
        return _norms_and_vecs.DoubleMap_clear(self)

    def get_allocator(self):
        return _norms_and_vecs.DoubleMap_get_allocator(self)

    def count(self, x):
        return _norms_and_vecs.DoubleMap_count(self, x)

    def erase(self, *args):
        return _norms_and_vecs.DoubleMap_erase(self, *args)

    def find(self, x):
        return _norms_and_vecs.DoubleMap_find(self, x)

    def lower_bound(self, x):
        return _norms_and_vecs.DoubleMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _norms_and_vecs.DoubleMap_upper_bound(self, x)
    __swig_destroy__ = _norms_and_vecs.delete_DoubleMap

# Register DoubleMap in _norms_and_vecs:
_norms_and_vecs.DoubleMap_swigregister(DoubleMap)

class IntVectorVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _norms_and_vecs.IntVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _norms_and_vecs.IntVectorVector___nonzero__(self)

    def __bool__(self):
        return _norms_and_vecs.IntVectorVector___bool__(self)

    def __len__(self):
        return _norms_and_vecs.IntVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _norms_and_vecs.IntVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _norms_and_vecs.IntVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _norms_and_vecs.IntVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _norms_and_vecs.IntVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _norms_and_vecs.IntVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _norms_and_vecs.IntVectorVector___setitem__(self, *args)

    def pop(self):
        return _norms_and_vecs.IntVectorVector_pop(self)

    def append(self, x):
        return _norms_and_vecs.IntVectorVector_append(self, x)

    def empty(self):
        return _norms_and_vecs.IntVectorVector_empty(self)

    def size(self):
        return _norms_and_vecs.IntVectorVector_size(self)

    def swap(self, v):
        return _norms_and_vecs.IntVectorVector_swap(self, v)

    def begin(self):
        return _norms_and_vecs.IntVectorVector_begin(self)

    def end(self):
        return _norms_and_vecs.IntVectorVector_end(self)

    def rbegin(self):
        return _norms_and_vecs.IntVectorVector_rbegin(self)

    def rend(self):
        return _norms_and_vecs.IntVectorVector_rend(self)

    def clear(self):
        return _norms_and_vecs.IntVectorVector_clear(self)

    def get_allocator(self):
        return _norms_and_vecs.IntVectorVector_get_allocator(self)

    def pop_back(self):
        return _norms_and_vecs.IntVectorVector_pop_back(self)

    def erase(self, *args):
        return _norms_and_vecs.IntVectorVector_erase(self, *args)

    def __init__(self, *args):
        _norms_and_vecs.IntVectorVector_swiginit(self, _norms_and_vecs.new_IntVectorVector(*args))

    def push_back(self, x):
        return _norms_and_vecs.IntVectorVector_push_back(self, x)

    def front(self):
        return _norms_and_vecs.IntVectorVector_front(self)

    def back(self):
        return _norms_and_vecs.IntVectorVector_back(self)

    def assign(self, n, x):
        return _norms_and_vecs.IntVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _norms_and_vecs.IntVectorVector_resize(self, *args)

    def insert(self, *args):
        return _norms_and_vecs.IntVectorVector_insert(self, *args)

    def reserve(self, n):
        return _norms_and_vecs.IntVectorVector_reserve(self, n)

    def capacity(self):
        return _norms_and_vecs.IntVectorVector_capacity(self)
    __swig_destroy__ = _norms_and_vecs.delete_IntVectorVector

# Register IntVectorVector in _norms_and_vecs:
_norms_and_vecs.IntVectorVector_swigregister(IntVectorVector)


def norm_square(nmax, alpha):
    return _norms_and_vecs.norm_square(nmax, alpha)

def teste_lista_aninhada(n):
    return _norms_and_vecs.teste_lista_aninhada(n)

def vector_n(nmax, alpha):
    return _norms_and_vecs.vector_n(nmax, alpha)

def vectorToNestedList(v):
    return _norms_and_vecs.vectorToNestedList(v)


